### ISSUE TITLE
[BUG] Fanyi Baidu – ADD A TITLE HERE

### ISSUE THREAD

**Issue by egaojing** [Fevol/obsidian-translate#46] opened 2023-04-04 01:49 UTC
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "macOS"
**framework_version**: "1.1.9"
**obsidian_version**: "1.1.16"

**Comment by Fevol** [comment] 2023-06-29 01:01
Closing this issue as it is an duplicate of #42.

**Closed by Fevol** 2023-06-29 01:01 UTC
Labels: bug
