### ISSUE TITLE
[feat] Translate on mod-enter

### ISSUE THREAD

**Issue by kometenstaub** [Fevol/obsidian-translate#4] opened 2022-06-23 20:53 UTC
It would be cool if the sidebar could execute the translation on mod-enter (ctrl-enter on windows/linux, cmd-enter on macOS).

**Comment by Fevol** [comment] 2022-06-23 23:36
Will be adding as soon as possible; I found a bug in the current implementation that makes the shortcut useless when it is located in the sidebar.

**Comment by Fevol** [comment] 2022-06-24 00:49
I've added release [1.1.2](https://github.com/Fevol/obsidian-translate/releases/tag/1.1.2) which adds the shortcut, be aware that the shortcut will not work when the Translation View is located in the sidebars if you're using a version earlier than 0.15

If you have any other suggestions for improving the translator workflow, do let me know!

**Comment by kometenstaub** [comment] 2022-06-24 07:52
It only executs on ctrl-shift-enter for me.

**Comment by kometenstaub** [comment] 2022-06-24 08:07
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/view.ts#L20
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/view.ts#L49
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/ui/translator-components/ViewPage.svelte#L186

This implementation doesn't look right.

---

Export this function:
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/ui/translator-components/ViewPage.svelte#L27


Modify the class:
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/view.ts#L11
```ts
export class TranslatorView extends ItemView {
	plugin: TranslatorPlugin;
	scope: Scope; // I'm not sure whether that's necessary
	private view: SvelteComponent;
	shortcut: KeymapEventHandler;

	constructor(leaf: WorkspaceLeaf, plugin: TranslatorPlugin) {
		super(leaf);
		this.plugin = plugin;
		this.scope.register(['Mod'], 'Enter', (evt: KeyboardEvent) => {
                   translate();
                   return false;
            })
	}

```

Compare [here](https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/2eb4a8b206a2d8b455dc556f3d797c92c440c258/src/ui/LOC/suggester.ts#L31) for an example.

There should also be no need to unregister it:
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/view.ts#L54

**Comment by Fevol** [comment] 2022-06-24 11:07
Thank you for the detailed issue!

> It only executs on ctrl-shift-enter for me.

Is it possible that your Translation View is located in one of the sidebars? If that's the case, the shortcut will indeed not work. 
This is fixed in build [0.15](https://forum.obsidian.md/t/obsidian-release-v0-15-0-insider-build/38948#:~:text=Sidebar%20panes%20can%20now%20receive%20focus.%20This%20change%20allows%20hotkeys%20to%20work%20in%20editors%20moved%20into%20the%20sidebar.), if the view is indeed in one of the sidebars, I'm afraid I can't fix the shortcut not working for versions <0.15.

---
> scope: Scope; // I'm not sure whether that's necessary`

Double checked this, and it seems to be necessary: the scope needs to be registered before any hotkeys can be assigned to it, otherwise, you would get an undefined error:
`Failed to open view TypeError: Cannot read properties of undefined (reading 'register')`

---
```ts
		this.scope.register(['Mod'], 'Enter', (evt: KeyboardEvent) => {
                   translate();
                   return false;
            })
```

That's a good point, currently the shortcut is triggered only when Cmd + Enter is pressed within the 'Translate from' text area. Would you rather have it translate even when the text area is not in focus?

---

> There should also be no need to unregister it:
https://github.com/Fevol/obsidian-translate/blob/79996a9a26bf0cd14b667aad6281a3d887d5487a/src/view.ts#L54

Haven't found anything saying that the shortcut would automatically get unregistered when the view is unloaded, it would make sense, but I'm not sure. I'll comment it out for now and ask around on Discord!

**Comment by kometenstaub** [comment] 2022-06-24 11:23
Alright, I tested in the sandbox vault, it works there. Then something is taking it in my main vault.
I think the issue might still be that you should return false with it.

**Comment by kometenstaub** [comment] 2022-06-24 11:36
I can't figure out for now what the issue with my main vault is or whether something could be optimised with how this plugin handles the keys, because I'm not familiar with svelte.

**Comment by Fevol** [comment] 2022-06-24 11:43
> Yes, I'm on 0.15 (I'm the one who told you about the sidebar), but it still doesn't work with only ctrl-enter for me. I'll test in a sandbox vault.

>I think the issue might still be that you should return false with it.

Ah sorry, didn't know you were the same person! Really strange that it's still causing issues, I'll try adding a quick release to add the `return false`, but you'll have to let me know if it works: I'm not able to reproduce the error as of now

> I can't figure out for now what the issue with my main vault is or whether something could be optimised with how this plugin handles the keys, because I'm not familiar with svelte.

From my (limited) understanding of Svelte, I don't think it could cause conflics with Obsidian's key handlers. Looking at the compiled code: this is how the textarea executes the key event: 
```js
        listen(textarea, "keydown", function() {
            if (is_function(ctx[4]))
              ctx[4].apply(this, arguments);
          })
```
Will do some more investigating & see if I can find a way to break it on my side

**Comment by Fevol** [comment] 2022-06-24 11:48
Quick update: 
```js
this.shortcut = this.scope.register(['Mod'], 'Enter', () => {
    return false;
});
```
This results in the command _not_ being executed, whereas `return true` does. I'm not sure what's going on here, to be frank

**Comment by kometenstaub** [comment] 2022-06-24 11:54
If you return false, yoh stop the hotkey from from being passed on. That would make sense when you call translate() before it. Right now, I  think your scope has no use, because you don't do anything with it. The logic for translating is in the event in svelte.

**Comment by kometenstaub** [comment] 2022-06-24 11:58
I use Ctrl-enter in my vault for toggling checkboxes in the editor. It might still consume it. Which is why I would make sense to use the scope.
When I used it in my plugins once, I also had to push it.

**Comment by Fevol** [comment] 2022-06-24 13:42
Another update: I don't think it's going to be possible to call ViewPage's translate() inside of view.ts: you can't export a function of a Svelte component as you need to be able to know the internal state of the component, and Svelte doesn't allow you to access this within a typescript file.

I also tried moving the scope to the component itself, but that just resulted in the command outright not working.

As for the issue, I'm really sorry, but I couldn't for the life of me reproduce it. I've tried multiple computers (both Windows), vaults, setups, locations of the view, ...; it always executed the translation. If you don't mind, I could send you a modified version of main.js containing some console.log's; I'm not sure if that will help with debugging, but I'm all out of ideas at this point.

**Comment by kometenstaub** [comment] 2022-06-24 14:02
Thank you for all your effort, I'll try it out in a bit. I have one idea left, in case it has to do with the Ctrl-enter hotkey I've set.
https://github.com/kometenstaub/obsidian-vim-reading-view-navigation/blob/26cc433a4e9afe7db8baa3966b1028d45c2a9cac/src/main.ts#L48

**Comment by kometenstaub** [comment] 2022-06-24 16:17
See #6, that solves it for me.

**Closed** 2022-06-24 17:00 UTC
Labels: enhancement

**Comment by kometenstaub** [comment] 2022-06-24 17:19
If you wanted to have the logic inside of the view, you could probably add the listeners directly to the textarea, the scope and push/pop to the top of the file where the script part is located.

**Comment by Fevol** [comment] 2022-06-24 21:16
@kometenstaub I've moved the event listeners to the View itself, does cause issues for you?

**Comment by kometenstaub** [comment] 2022-06-24 21:24
Yes, it works. :)

**Comment by kometenstaub** [comment] 2022-06-24 21:25
It's even better now that the hotkeys works when the mouse is anywhere on the pane :heart:
